version: '3.8'

services:
  app:
    image: openjdk:17-jdk-alpine
    container_name: ticketing-service-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    volumes:
      - .:/app
    command: ["java", "-jar", "/app/target/ticketing-service-0.0.1-SNAPSHOT.jar"]

  # en este caso no configuramos un contenedor de base de datos porque
  # estás utilizando una base de datos H2 en memoria